services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: port5432
      POSTGRES_DB: book_contacts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:port5432@db:5432/book_contacts
    ports:
      - "8000:8000"

volumes:
  pgdata:

